### ISSUE TITLE
Zookeeper Role stuck in retry loop if the zookeeper mode is standalone

### ISSUE THREAD

**Issue by andrem123456** [humio/ansible-zookeeper#16]
This task here 
https://github.com/humio/ansible-zookeeper/blob/6050e285dff5b07e36ca400b6f19a8b1aaa1f5fa/tasks/main.yml#L112-L119

Should include standalone mode too as Zookeeper is up but since it is a single instance it doesn't fall under follower or leader mode.

**Comment by srdo** [comment]
Nice catch. Do you want to open a PR to fix it? Otherwise I'm happy to push a fix.

**Comment by schofield** [comment]
Fixed in https://github.com/humio/ansible-zookeeper/commit/0ee10299a48193e9701fa8c8df5079833b45b8dd
