### ISSUE TITLE
Upgrading Zookeeper to 3.5.6 fails

### ISSUE THREAD

**Issue by srdo** [humio/ansible-zookeeper#5]
When upgrading Zookeeper using this script, the upgraded Zookeeper may fail to start due to the issue described in https://issues.apache.org/jira/browse/ZOOKEEPER-3056

The workaround is to add the line `zookeeper.snapshot.trust.empty=true` to `zoo.cfg` and start each Zookeeper node once. After this, the line can be removed again.

I think we should make the install script do this automatically if upgrading from a 3.4.x to 3.5.6.

**Comment by schofield** [comment]
I hadn't run into this issue on some previous upgrades, since it's noted in the documentation for now will close this and make a new issue for detecting the upgrade.

**Comment by srdo** [comment]
If you have a good idea for automating this, go for it. If not, the addition of `snapshot_trust_empty` in https://github.com/humio/ansible-zookeeper/pull/11/files should hopefully make it easy for customers to do manually. I'm updating the docs to mention this here https://github.com/humio/docs.humio.com/pull/943

**Comment by schofield** [comment]
I have some ideas but the way I've done it in the past is pretty clunky. I think the docs are a sufficient way to handle in the immediate case.
