### ISSUE TITLE
Four-letter words are deprecated

### ISSUE THREAD

**Issue by srdo** [humio/ansible-zookeeper#9]
Zookeeper has deprecated the 4-letter words (e.g. "ruok").

The alternative is to use the admin server, which we support here https://github.com/humio/ansible-zookeeper/blob/master/templates/zoo.cfg.j2#L15

I don't think we should whitelist the 4LW as we do here https://github.com/humio/ansible-zookeeper/blob/master/templates/zoo.cfg.j2#L7, do we even need them? Humio accesses ZK through the admin server.

**Comment by schofield** [comment]
When this isn't enabled the Zookeeper cluster admin page errors, does it support admin server now?

**Comment by srdo** [comment]
I was wrong, we still use the four-letter words https://github.com/humio/humio/blob/e4646d0893b419b7fd3fbc4b7161fb0aeda15f05/src/main/scala/com/humio/zookeeper/ZookeeperStatsClient.scala#L70-L94.

Maybe it's better to postpone addressing this until we can ask customers to run at least Zookeeper 3.5.x, at which point we can update the job to use the adminserver. I'll close this for now, since I don't think we require 3.5.x for any other reason yet.
